import {
  Body,
  Controller,
  Get,
  Headers,
  HttpCode,
  HttpStatus,
  Param,
  Post,
  Req,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiHeader,
  ApiParam,
} from '@nestjs/swagger';
import type { Request } from 'express';
import { PaymentsService } from './payments.service';
import { WebhookService } from './webhook.service';
import { CreatePaymentDto } from './dto/create-payment.dto';

@ApiTags('Payments')
@Controller('payments')
export class PaymentsController {
  constructor(
    private readonly paymentsService: PaymentsService,
    private readonly webhookService: WebhookService,
  ) {}

  @Post()
  @ApiOperation({
    summary: 'Create Payment Order',
    description:
      'Creates a PaymentOrder in DB, registers order with Cashfree PG Sandbox (POST /pg/orders), and returns payment_session_id for client checkout.',
  })
  @ApiHeader({
    name: 'idempotency-key',
    required: false,
    description: 'Unique client key to prevent accidental duplicate payment orders',
  })
  @ApiResponse({
    status: 201,
    description: 'Payment order created successfully with payment session info',
  })
  async createPayment(
    @Body() dto: CreatePaymentDto,
    @Headers('idempotency-key') idempotencyKey?: string,
  ) {
    return this.paymentsService.createPayment(dto, idempotencyKey);
  }

  @Get(':orderId')
  @ApiOperation({
    summary: 'Get Payment Status by Order ID',
    description:
      'Retrieves the current status, transaction attempts, and payment order details from ERP database.',
  })
  @ApiParam({ name: 'orderId', example: 'UMS_1791372850123_8AB9C2' })
  @ApiResponse({
    status: 200,
    description: 'Payment order details',
  })
  @ApiResponse({
    status: 404,
    description: 'Payment order not found',
  })
  async getPayment(
    @Param('orderId') orderId: string,
  ) {
    return this.paymentsService.getPayment(orderId);
  }

  @Post(':orderId/verify')
  @ApiOperation({
    summary: 'Verify & Reconcile Payment against Cashfree Gateway',
    description:
      'Fetches current status directly from Cashfree PG API, verifies state machine transition, and synchronizes ERP database status.',
  })
  @ApiParam({ name: 'orderId', example: 'UMS_1791372850123_8AB9C2' })
  @ApiResponse({
    status: 200,
    description: 'Payment verified and status synchronized',
  })
  async verifyPayment(
    @Param('orderId') orderId: string,
  ) {
    return this.paymentsService.verifyPayment(orderId);
  }

  @Post('webhook/cashfree')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Cashfree Webhook Listener',
    description:
      'Receives signed webhook notifications directly from Cashfree PG, verifies HMAC-SHA256 signature, prevents duplicate replays via idempotency, and updates order & transaction statuses.',
  })
  @ApiHeader({
    name: 'x-webhook-signature',
    required: true,
    description:
      'Base64 encoded HMAC-SHA256 signature generated by Cashfree using client secret key',
  })
  @ApiHeader({
    name: 'x-webhook-timestamp',
    required: true,
    description: 'Timestamp header passed by Cashfree',
  })
  @ApiResponse({
    status: 200,
    description: 'Webhook processed successfully or duplicate recognized',
  })
  @ApiResponse({
    status: 401,
    description: 'Unauthorized: Invalid Cashfree webhook signature',
  })
  async cashfreeWebhook(
    @Req() req: Request & { rawBody?: Buffer },
    @Body() body: any,
    @Headers('x-webhook-signature') signature: string,
    @Headers('x-webhook-timestamp') timestamp: string,
  ) {
    return this.webhookService.processCashfreeWebhook(
      body,
      req.rawBody!,
      signature,
      timestamp,
    );
  }
}
